### ISSUE TITLE
upload? related problem when debugging

### ISSUE THREAD

**Issue by ktkarhu** [aalto-trafficsense/regular-routes-client#23]
When debugging with my branch I get the following error after some time:
02-09 09:42:04.647  15838-15862/? E/AndroidRuntime﹕ FATAL EXCEPTION: PipelineThread
    Process: fi.aalto.trafficsense.regularroutes, PID: 15838
    java.lang.IllegalStateException: call from invalid thread
            at com.google.common.base.Preconditions.checkState(Preconditions.java:173)
            at fi.aalto.trafficsense.regularroutes.util.ThreadGlue.verify(ThreadGlue.java:26)
            at fi.aalto.trafficsense.regularroutes.util.ThreadGlue.verify(ThreadGlue.java:22)
            at fi.aalto.trafficsense.regularroutes.backend.rest.RestClient.uploadData(RestClient.java:93)
            at fi.aalto.trafficsense.regularroutes.backend.pipeline.PipelineThread$1$2.run(PipelineThread.java:85)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by jannesuo** [comment]
ThreadGlue was helper class that Joonas added earlier to verify that the execution happens in the thread that we expect it to. Seems like it is not the case. 

If you need to work with something, you can just comment the line where threadGlue.verify() is called and it won't affect on any functionality.

**Comment by Gekkio** [comment]
Yeah, the PipelineThread constructor was running in a different thread. It's not really an issue, but I refactored the code to run the constructor in the same thread that the PipelineThread will use for operations.
